apiVersion: v1
kind: Pod
metadata:
  name: hostaliases-pod
spec:
  hostAliases:
  - ip: "172.18.40.171"
    hostnames:
    - "kibana.secure.verinovum.com"
  containers:
    - name: test
      image: nginx
