kubectl exec -it -n elk elasticsearch-master-0 sh
/bin/elasticsearch-certutil ca --out /tmp/elastic-stack-ca.p12 --pass ''
/bin/elasticsearch-certutil cert --name elasticsearch-master --dns elasticsearch-master --ca /tmp/elastic-stack-ca.p12 --pass '' --ca-pass '' --out /tmp/elastic-certificates.p12
exit
kubectl cp -n elk elasticsearch-master-0:/tmp/elastic-certificates.p12 ./
openssl pkcs12 -nodes -passin pass:'' -in elastic-certificates.p12 -out elastic-certificate.pem
openssl x509 -outform der -in elastic-certificate.pem -out elastic-certificate.crt
kubectl delete secret -n elk elastic-certificate-pem
kubectl delete secret -n elk elastic-certificate-crt
kubectl delete secret -n elk elastic-certificates
kubectl create secret generic elastic-certificates --from-file=elastic-certificates.p12  -n elk
kubectl create secret generic elastic-certificate-pem --from-file=elastic-certificate.pem -n elk
kubectl create secret generic elastic-certificate-crt --from-file=elastic-certificate.crt -n elk
