kubectl exec -it -n elk elasticsearch-master-0 sh
bin/elasticsearch-certutil ca --out /tmp/elastic-stack-ca.p12 --pass changeit
bin/elasticsearch-certutil cert --name elasticsearch-master --dns elasticsearch-master --ca /tmp/elastic-stack-ca.p12 --pass changeit --ca-pass changeit --out /tmp/elastic-certificates.p12
exit
kubectl cp -n elk elasticsearch-master-0:/tmp/elastic-certificates.p12 /tmp/elastic.p12
cp /tmp/elastic.p12 elastic-certificates.p12
openssl pkcs12 -nodes -passin pass:changeit -in elastic-certificates.p12 -out elastic-certificate.pem
openssl x509 -outform der -in elastic-certificate.pem -out elastic-certificate.crt
kubectl delete secret -n elk elastic-certificate-pem
kubectl delete secret -n elk elastic-certificate-crt
kubectl delete secret -n elk elastic-certificates
kubectl create secret generic elastic-certificates --from-file=elastic-certificates.p12  -n elk
kubectl create secret generic elastic-certificate-pem --from-file=elastic-certificate.pem -n elk
kubectl create secret generic elastic-certificate-crt --from-file=elastic-certificate.crt -n elk


          - name: "ELASTICSEARCH_HOSTS"
            value: "https://elasticsearch-master:9200"

    server.ssl.certificate: /usr/share/kibana/config/certs2/elastic-certificate.pem
    server.ssl.key: /usr/share/kibana/config/certs2/elastic-certificate.pem


elasticsearch.ssl.certificateAuthorities: [ "/usr/share/kibana/config/certs2/elastic-certificate.pem" ]
elasticsearch.ssl.verificationMode: none
elasticsearch.hosts: ["https://elasticsearch-master:9200"]


    xpack.security.authProviders: [saml, basic]
    server.xsrf.whitelist: [/api/security/v1/saml]


            native1:
                type: native
                order: 0

    xpack:
      security:
        authc:
          realms:
            native1:
                type: native
                order: 0
            saml1:
              type: saml
              order: 2
              idp.metadata.path: "/usr/share/elasticsearch/config/Elasticsearch.xml"
              idp.entity_id: "AZURE_AD_IDENTIFIER_URL"
              sp.entity_id:  "https://KIBANA_URL:5601/"
              sp.acs: "https://KIBANA_URL:5601/api/security/v1/saml"
              sp.logout: "https://KIBANA_URL:5601/logout"
              attributes.principal: nameid
              attributes.groups: "http://schemas.microsoft.com/ws/2008/06/identity/claims/role"

https://appdevmusings.com/azure-kubernetes-service-aks-azure-ad-saml-based-single-sign-on-to-secure-elasticsearch-and-kibana-and-securing-communications-in-elk
